let normalForm = [
  {
    vModel: "department",
    label: "申请人部门",
    i18n: true,
    type: "select",
    contentType: "text",
    changeEvent: false,
    changeEventName: "departmentChange",
    changeEventQueryMethod: "post",
    changeEventQueryPath: "/mes/api/show/time",
    changeEventQueryParams: ["factory", "process", "line"],
    required: true,
    multiple: false,
    filterable: true,
    template: false,
  },
  {
    vModel: "process",
    label: "申请工序",
    i18n: true,
    type: "select",
    contentType: "text",
    changeEvent: false,
    changeEventName: "departmentChange",
    changeEventQueryMethod: "post",
    changeEventQueryPath: "/mes/api/show/time",
    changeEventQueryParams: ["factory", "process", "line"],
    required: true,
    multiple: false,
    filterable: true,
    template: false,
  },
  {
    vModel: "workNo",
    label: "申请人工号",
    i18n: true,
    type: "input",
    contentType: "text",
    changeEvent: false,
    changeEventName: "departmentChange",
    changeEventQueryMethod: "post",
    changeEventQueryPath: "/mes/api/show/time",
    changeEventQueryParams: ["factory", "process", "line"],
    required: true,
    multiple: false,
    filterable: true,
    template: false,
  },
  {
    vModel: "name",
    label: "申请人",
    i18n: true,
    type: "input",
    contentType: "text",
    changeEvent: false,
    changeEventName: "departmentChange",
    changeEventQueryMethod: "post",
    changeEventQueryPath: "/mes/api/show/time",
    changeEventQueryParams: ["factory", "process", "line"],
    required: true,
    multiple: false,
    filterable: true,
    template: false,
  },
  {
    vModel: "lockProcess",
    label: "申请人",
    i18n: true,
    type: "select",
    contentType: "text",
    changeEvent: false,
    changeEventName: "departmentChange",
    changeEventQueryMethod: "post",
    changeEventQueryPath: "/mes/api/show/time",
    changeEventQueryParams: ["factory", "process", "line"],
    required: false,
    multiple: false,
    filterable: true,
    template: false,
  },
  {
    vModel: "qty",
    label: "申请数量",
    i18n: true,
    type: "input",
    contentType: "number",
    changeEvent: false,
    changeEventName: "departmentChange",
    changeEventQueryMethod: "post",
    changeEventQueryPath: "/mes/api/show/time",
    changeEventQueryParams: ["factory", "process", "line"],
    required: false,
    multiple: false,
    filterable: true,
    template: false,
  },
];

export default normalForm;
