const normalTable = [
  {
    prop: "sn",
    label: "sn号",
    i18n: false,
    formatter: "",
    fixed: "center",
    index: false,
    edit: false,
    editPagePath: "/cusSpotCheckWhitelist/edit/${item.id}",
    del: false,
    delQueryPath: "mesSpotCheckWhitelist",
    export: false,
    exportQueryPath: "mesSpotCheckWhitelist",
    template: false,
  },
  {
    prop: "matNo",
    label: "物料号",
    i18n: false,
    width: "",
    formatter: "",
    fixed: "center",
    index: false,
    edit: false,
    editPagePath: "/cusSpotCheckWhitelist/edit/${item.id}",
    del: false,
    delQueryPath: "mesSpotCheckWhitelist",
    export: false,
    exportQueryPath: "mesSpotCheckWhitelist",
    template: false,
  },
  {
    prop: "process",
    label: "工序",
    i18n: false,
    width: "",
    formatter: "",
    fixed: "center",
    index: false,
    edit: false,
    editPagePath: "/cusSpotCheckWhitelist/edit/${item.id}",
    del: false,
    delQueryPath: "mesSpotCheckWhitelist",
    export: false,
    exportQueryPath: "mesSpotCheckWhitelist",
    template: false,
  },
];

export default normalTable;
